/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FreeNote = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'category' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'studentName' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
  'course' : IDL.Text,
});
export const YouTubeLecture = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFreeNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addYouTubeLecture' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteFreeNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteYouTubeLecture' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getFreeNotes' : IDL.Func([], [IDL.Vec(FreeNote)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getYouTubeLectures' : IDL.Func([], [IDL.Vec(YouTubeLecture)], ['query']),
  'submitReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FreeNote = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'category' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'studentName' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
    'course' : IDL.Text,
  });
  const YouTubeLecture = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addFreeNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addYouTubeLecture' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteFreeNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteYouTubeLecture' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getFreeNotes' : IDL.Func([], [IDL.Vec(FreeNote)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getYouTubeLectures' : IDL.Func([], [IDL.Vec(YouTubeLecture)], ['query']),
    'submitReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };